server:
  port: 31200
spring:
  application:
    name: xc-service-manage-course

mybatis:
  #pojo别名扫描包
  type-aliases-package: com.xuecheng.framework.domain
  mapper-locations: classpath:com/xuecheng/manage_course/dao/*Mapper.xml

pagehelper:
    helper-dialect: mysql  #数据库
    reasonable: true
    support-methods-arguments: true
    params: count=countSql

eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: ${EUREKA_SERVER:http://localhost:50101/eureka/}
  instance:
    prefer‐ip‐address:  true  #将自己的ip地址注册到Eureka服务中
    ip‐address: ${IP_ADDRESS:127.0.0.1}
    instance‐id: ${spring.application.name}:${server.port} #指定实例id