server:
  port: 31200
spring:
  application:
    name: xc-service-manage-course

mybatis:
  #pojo别名扫描包
  type-aliases-package: com.xuecheng.framework.domain
  mapper-locations: classpath:com/xuecheng/manage_course/dao/*Mapper.xml
